#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

picom
firefox
polybar
bspc rule -a xdg-desktop-portal-gtk state=floating
bspc rule -a steam state=floating
